### ISSUE TITLE
Tutorial 2 lesson 4: number and spam interpretation

### ISSUE THREAD

**Issue by grover4** [OpenIntroStat/ims-tutorials#124]
Could there be a problem with the interpretation here? The question asks for what's **not valid**.  The third answer - Given that an email contains a big number, it is more likely to be **not** spam - seems valid, so should it be marked as correct=TRUE? I also don't follow the message for "incorrect=Given the kind of number an email contains, we can't say whether it'll be more or less likely to be spam".  This seems like precisely what we can say from a segmented bar chart. 

```{r mc4}
question("Which of the following interpretations of the plot **is not** valid?",
  answer("Given that an email contains a small number, it is more likely to be 
not spam"),
  answer("Given that an email contains no number, it is more likely to be spam.", correct = TRUE),
  answer("Given that an email contains a big number, it is more likely to be not spam.", correct = TRUE),
  answer("Within both spam and not spam, the most common number is a small one.", message = "Wrong!"),
  incorrect = "Given the kind of number an email contains, we can't say whether it'll be more or less likely to be spam.",
  allow_retry = TRUE
)
```

**Comment by mine-cetinkaya-rundel** [comment]
Thank you. I have updated the question and the plots provided and fixed the answer. Will redeploy shortly.
