### ISSUE TITLE
Exploratory data analysis: 1 - Exploring categorical data

### ISSUE THREAD

**Issue by monika76five** [OpenIntroStat/ims-tutorials#125]
In "Exploring categorical data", where it is stated that "The contingency table from the last exercise is available in your workspace as tab", I don't seem to find tab in the workspace.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks, we'll take a look.

To make it easier to follow up, here is the relevant place in the source code:

https://github.com/OpenIntroStat/ims-tutorials/blob/443082a85da3a01c7b136ba82b8f0ab19f96b38e/02-explore/01-lesson/02-01-lesson.Rmd#L264-L292

The `tab` object should be available in the subsequent code chunk based on the setup chunk.

**Comment by mine-cetinkaya-rundel** [comment]
@monika76five See below, `tab` seems to be there. Am I looking in the right place?

<img width="1389" alt="Screen Shot 2021-09-13 at 3 19 00 PM" src="https://user-images.githubusercontent.com/5965649/133143603-a58e454c-87da-4ded-9bb0-b692b6583a7c.png">

**Comment by monika76five** [comment]
Thanks! I ran it again and it is indeed there - not sure what happened earlier. Thanks for the quick response!
