### ISSUE TITLE
Exploratory data analysis: 1 - Exploring categorical data; pie chart not showing up

### ISSUE THREAD

**Issue by monika76five** [OpenIntroStat/ims-tutorials#126]
In Exploratory data analysis: 1 - Exploring categorical data, Distribution of one variable, the figure for the section titled "Pie chart vs. bar chart" does not show up.

**Comment by mine-cetinkaya-rundel** [comment]
Is it this one?

<img width="1491" alt="Screen Shot 2021-09-13 at 7 51 00 PM" src="https://user-images.githubusercontent.com/5965649/133171611-046b1db8-77ac-4097-9ae1-553007650738.png">

**Comment by monika76five** [comment]
Yep and when I opened it now, it worked... Not sure why... Sometimes it
does take time for the tutorial pages to load, so I couldn't tell whether
it is the loading issue or something is missing.

**Comment by mine-cetinkaya-rundel** [comment]
Odd, closing for now, but let me know if this persist with good internet.
