### ISSUE TITLE
High traffic on ShinyApps

### ISSUE THREAD

**Issue by lbelzile** [OpenIntroStat/ims-tutorials#129]
Many thanks for putting all this material together. I had assigned the tutorials for my class, but the IMS tutorials are seemingly too popular: the Shiny server window stays stuck at "Please wait" nearly indefinitively.

Outside of increasing capacity (which costs money), is there any alternative way to access the tutorials? e.g., I normally bundle my `learnr` files in a package that can be installed locally.

**Comment by mine-cetinkaya-rundel** [comment]
Which tutorials, in particular, are doing this? It's possible that I can increase capacity further. If not, we'll go the package route.

**Comment by lbelzile** [comment]
[Getting Started with Data: 3 - Sampling strategies and Experimental design](https://openintro.shinyapps.io/ims-01-data-03/) is the one that seems never to be available. Others from that section are intermittent, but do work often enough.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks, I just restarted that tutorial and it seems to be working now.

Do let me know if you're experiencing the same thing again though. We can increase capacity is the current setup is causing difficulty.

**Comment by lbelzile** [comment]
Many thanks Mine!
