### ISSUE TITLE
Tutorial 3 Lesson 3 Understanding Linear Models 

### ISSUE THREAD

**Issue by juliaparish** [OpenIntroStat/ims-tutorials#135]
For Tutorial 3 Lesson 3 Understanding Linear Models section, within the Your Turn! portion, should the answer comment read
"The E represents the noise and the beta0 represents the y-intercept."

[
<img width="1097" alt="Screen Shot 2021-12-21 at 3 35 35 PM" src="https://user-images.githubusercontent.com/88252036/147020479-2b898669-4e09-4c88-be4a-e15cd945d3fe.png">
](url)

**Comment by mine-cetinkaya-rundel** [comment]
Corrected to say `beta_0 represents the y-intercept`.
