### ISSUE TITLE
ims-01-lesson-02 missing UCBAdmissions dataset

### ISSUE THREAD

**Issue by hardin47** [OpenIntroStat/ims-tutorials#140]
From Barbara Dolansky   bdolansky@vassar.edu

Hello -

I am working through Lesson 2 of Tutorial 1 (IMS) and am creating an R script for myself with all of the code. However, I am unable to find the dataset ucb_admit. It is preloaded in the tutorial so it works fine there, but I cannot recreate the code in my own R script. I have found the UCBAdmissions dataset online that has frequencies for each gender and admission status by department, but when I look through the datasets in the openintro package I do not see anything listed that looks like the ucb_admit dataset. Is there any way for me to get this dataset?

Thanks very much for your help.

Take care -
Barbara

**Comment by hardin47** [comment]
the us_regions dataset was also not available

**Comment by mamcisaac** [comment]
https://github.com/OpenIntroStat/ims-tutorials/tree/master/01-data/02-lesson/data

https://github.com/OpenIntroStat/ims-tutorials/tree/master/01-data/03-lesson/data
