### ISSUE TITLE
tutorials down?

### ISSUE THREAD

**Issue by beanumber** [OpenIntroStat/ims-tutorials#160]
https://openintro.shinyapps.io/ims-03-model-08/

I see:
```
An error has occurred

The application failed to start.

exit status 1
```

**Comment by mine-cetinkaya-rundel** [comment]
I’ll try redeploying in the next hourSent from my iPhoneOn 29 Sep 2022, at 12:20, Ben Baumer ***@***.***> wrote:﻿
https://openintro.shinyapps.io/ims-03-model-08/
I see:
An error has occurred

The application failed to start.

exit status 1

**Comment by mine-cetinkaya-rundel** [comment]
this should be up and running now

**Comment by beanumber** [comment]
Thank you!
