### ISSUE TITLE
01-01-lesson: ordinal vs. nominal

### ISSUE THREAD

**Issue by ChrisBogner** [OpenIntroStat/ims-tutorials#162]
Dear authors,

Thank you so much for the great material! I have a suggestion on terms. Section "Categorical data": "If the levels of a categorical variable do not have an inherent ordering to them, then the variable is simply called categorical. For example, do you consume caffeine or not?"
I think, this should read "...do not have an inherent ordering to them, then the variable is called nominal...", because ordinal and nominal are the two types of a categorical variable.

Regards,

Christina

**Comment by npaterno** [comment]
Thanks Christina! I've made this adjustment to the tutorial. 

Best, 
~N
