### ISSUE TITLE
Problem with Tutorial 2 - Visualizing numerical data

### ISSUE THREAD

**Issue by ChrisBogner** [OpenIntroStat/ims-tutorials#163]
Dear authors,

I get an error in the chapter "Colored density plots" when I run the chunk at the very end of the chapter. This happens in the tutorial started from the book here https://openintrostat.github.io/ims-tutorials/.

The chunk
# Create overlaid density plots for same data
ggplot(data = common_cyl, aes(x = city_mpg, fill = as.factor(ncyl))) +
  geom_density(alpha = 0.3)

produced the error "object 'common_cyl' not found". This error does not reproduce when I run the version downloaded from GitHub.

Thanks,

Christina

**Comment by mamcisaac** [comment]
I believe this issue was fixed by #175 and should be closed.
