### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by ChrisBogner** [OpenIntroStat/ims-tutorials#165]
Dear authors,

I found the following typos:

Regression modeling: 2 - Correlation, Pearson Product-Moment Correlation. The formula is incorrect; the square roots are missing in the denominator.

Regression modeling: 4 - Interpreting regression models, Quiz Units and scale. In the answer, it reads: -105.011+ (1.018 * 170) = 60.049. However, it should read: -105.011+ (1.018 * 170) = 68.049

Regards,

Christina Bogner

**Comment by npaterno** [comment]
Hi Christina, 

Thanks for catching these! They've been addressed. 

Best, 
~Nick
