### ISSUE TITLE
Convert `%>%` to `|>` throughout

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims-tutorials#168]
The tutorial triaging project seems like a good time to make the jump from `%>%` to `|>` @npaterno. In general, this could be a Find and Replace All, but there are two possible places it might require more work:

- Where we explain what the pipe operator is
- Modeling-ish bits where `.` is used as a placeholder to what's coming from the pipe's previous step, since that's where the behaviour of the two pipe operators differ

**Comment by npaterno** [comment]
@mine-cetinkaya-rundel Working on this one now. Should be done by end of the week.
