### ISSUE TITLE
missing code in Tutorial Exploratory 4-Case Study

### ISSUE THREAD

**Issue by GermanAltgelt** [OpenIntroStat/ims-tutorials#171]
it seems you are missing the chain you are referring to, perhaps you turned the echo off in RMarkdown
"Exploratory data analysis: 4 - Case study
Answering questions with chains
When you have a specific question about a dataset, you can find your way to an answer by carefully constructing the appropriate chain of R code. For example, consider the following question:

“Within non-spam emails, is the typical length of emails shorter for those that were sent to multiple people?”

This can be answered with the following chain:"

and the missing chain is, I think:
email %>%
    filter(spam == 0) %>%
    group_by(to_multiple) %>%
    summarize(median(num_char))

**Comment by mamcisaac** [comment]
@GermanAltgelt, I saw your issue, so I copied the code for the tutorials, modified it to fix the issue that you highlighted, and offered it back to the OpenIntroStat group. They will review my pull request, and once they have had a chance to ensure that I haven't accidentally introduced any new bugs, they can choose to merge my changes into the "real code" that runs the tutorials. You will only see changes in the "published" tutorials after that happens.
