### ISSUE TITLE
[Bug]:  https://openintrostat.github.io/ims-tutorials/ is reporting a 404 error.

### ISSUE THREAD

**Issue by mamcisaac** [OpenIntroStat/ims-tutorials#196]
### Contact Details

mmcisaac@upei.ca

### Bug

The website https://openintrostat.github.io/ims-tutorials/ is reporting a 404 error. 

The end-of-lesson links to the "Full list of tutorials supporting OpenIntro::Introduction to Modern Statistics" seems to be broken since the latest redeployment. 

<img width="597" alt="Screenshot 2023-08-28 at 10 51 35 AM" src="https://github.com/OpenIntroStat/imstutorials/assets/55292798/1dc6e0f3-3906-4267-9e88-67101a53af46">

### Reproducible Example

https://openintrostat.github.io/ims-tutorials/

### Expected Behavior

The link should open a website displaying the "Full list of tutorials supporting OpenIntro::Introduction to Modern Statistics"

**Comment by mine-cetinkaya-rundel** [comment]
Thank you, I expected GitHub to redirect but seems like it didn't work. They're at https://openintrostat.github.io/imstutorials/.

I'll look into a redirect as well.

**Comment by mamcisaac** [comment]
The end-of-lesson "Congratulations!" pages all use the old links. E.g., 

>r emo::ji("ledger")` [Full list of tutorials supporting OpenIntro::Introduction to Modern Statistics](https://openintrostat.github.io/ims-tutorials/)

> `r emo::ji("spiral_notepad")` [Tutorial 1: Introduction to data](https://openintrostat.github.io/ims-tutorials/01-data/)

uses the links
https://openintrostat.github.io/ims-tutorials/
and
https://openintrostat.github.io/ims-tutorials/01-data/

**Comment by mamcisaac** [comment]
This just cropped up again. 

Now none of the "tutorial level" links are working (e.g., https://openintrostat.github.io/ims-tutorials/03-model/, https://openintrostat.github.io/ims-tutorials/04-foundations/, etc.). These all result in 404 errors.

**Comment by mine-cetinkaya-rundel** [comment]
@mamcisaac I think they're back up, there seemed to be an issue with GitHub Pages building momentarily.
