### ISSUE TITLE
[Bug]: Tutorial 3 lesson 10 error in pairs(nyc) solution

### ISSUE THREAD

**Issue by mamcisaac** [OpenIntroStat/ims-tutorials#197]
### Contact Details

mmcisaac@upei.ca

### Bug

In lesson 10 of Tutorial 3 (Case study), the solution in the "ex1-solution" chunk is 

pairs(nyc)

but this leads to an error: 

"non-numeric argument to 'pairs' "

<img width="803" alt="Screenshot 2023-09-21 at 2 24 08 PM" src="https://github.com/OpenIntroStat/ims-tutorials/assets/55292798/cc1b2da0-2e12-4d96-b628-0c2d6191aefc">

In order for the code to work, we need to focus on only the numeric variables. I.e., the solution should be something like 

pairs(~Case+Price+Food+Decor+Service+East, nyc)

or 

pairs(nyc %>% select(-Restaurant))

### Reproducible Example

nyc <- read_csv("data/nyc.csv")

pairs(nyc)

### Expected Behavior

A matrix of scatterplots is produced.

**Comment by mine-cetinkaya-rundel** [comment]
Thank you!
