### ISSUE TITLE
Issue with Tutorial 2

### ISSUE THREAD

**Issue by kyraservoss** [OpenIntroStat/ims-tutorials#205]
It doesn't look like the completion of the first section is being recorded in tutorial 2. I have run the code several times and the table has appeared; however, when I reload the page and go back there seems to be some sort of internal error. (see attached screenshot)

<img width="839" alt="Screenshot 2023-09-04 at 10 51 01 PM" src="https://github.com/OpenIntroStat/ims/assets/144079277/ef486f76-ff07-4adb-9a0b-ca66b17bed6e">

**Comment by mine-cetinkaya-rundel** [comment]
I can't seem to reproduce this issue anymore so I'll close this for now. If it comes back we can revisit.
