### ISSUE TITLE
The missed button in tutorial: 05_infer_02

### ISSUE THREAD

**Issue by LingjiaZhu** [OpenIntroStat/ims-tutorials#215]
I found tutorial: 05_infer_04 seems to miss something. This chunk in the picture has nowhere to run and get the result. Thus, I think if you can add it, the following question would be better to solve.

**Comment by mamcisaac** [comment]
The p-value is given just above the provided screenshot:

<img width="676" alt="Screenshot 2023-11-11 at 8 55 59 PM" src="https://github.com/OpenIntroStat/ims-tutorials/assets/55292798/3b257970-acd3-4df7-9ae1-07e52792f957">
