### ISSUE TITLE
Suggestion for adding a definition of "cell"

### ISSUE THREAD

**Issue by jqzjqz0707** [OpenIntroStat/ims-tutorials#223]
The concept "cell" first appeared in tutorial 05-infer-03 and continued in tutorial 05-infer-04. People may still confused about it. So, maybe it is proper to add an explanation about this concept when it is mentioned for the first time.

**Comment by mine-cetinkaya-rundel** [comment]
Thanks! I added a bit of clarification, but since concept is introduced in the book I won't add too much more here.
