### ISSUE TITLE
Issue w/ ims-05-infer-03 exercise

### ISSUE THREAD

**Issue by senecarussell** [OpenIntroStat/ims-tutorials#235]
When I try and complete the exercise "Building two null distributions" in 05-infer-03, I receive this error message. I tried copying the code directly from the hint box as well and it still gives me the same error that chi_obs_spac is not found. 
<img width="922" alt="Screen Shot 2023-11-16 at 1 57 22 AM" src="https://github.com/OpenIntroStat/ims/assets/146801999/da325b3c-7951-4b40-989d-9c529216ed7c">

**Comment by mine-cetinkaya-rundel** [comment]
The first one is now fixed.

<img width="903" alt="Screenshot 2023-11-16 at 4 38 48 PM" src="https://github.com/OpenIntroStat/ims-tutorials/assets/5965649/3ac5616a-6897-415d-bb73-a14e9ff6df68">

Can you clarify where in tutorial 4 issue arises?

**Comment by senecarussell** [comment]
I get the same error for p_benford in the "Goodness of Fit Test" code chunk, both code chunks in "A p-value, two ways" for first_digit and null, and all 3 code chunks for "Testing Iowa" for p_benford and iowa_county. I have included pictures below
<img width="922" alt="Screen Shot 2023-11-16 at 1 57 22 AM" src="https://github.com/OpenIntroStat/ims-tutorials/assets/146801999/91f98d3c-cfba-4dbe-a403-3302239e3999">
<img width="1393" alt="Screen Shot 2023-11-16 at 8 33 19 PM" src="https://github.com/OpenIntroStat/ims-tutorials/assets/146801999/5f298c3d-ddef-40bf-9f65-e90421536d78">
<img width="1416" alt="Screen Shot 2023-11-16 at 8 33 34 PM" src="https://github.com/OpenIntroStat/ims-tutorials/assets/146801999/40f3b055-a5e2-4ec7-be5f-4dc99866e044">
<img width="1432" alt="Screen Shot 2023-11-16 at 8 33 53 PM" src="https://github.com/OpenIntroStat/ims-tutorials/assets/146801999/4120d519-161d-4098-baed-7b9f0d84d675">
<img width="1432" alt="Screen Shot 2023-11-16 at 8 34 02 PM" src="https://github.com/OpenIntroStat/ims-tutorials/assets/146801999/4d5386a9-087b-4d9c-a430-bff107c77428">

**Comment by mine-cetinkaya-rundel** [comment]
This should now be fixed, and the tutorial is deploying. Thanks for reporting!
