### ISSUE TITLE
Add definitions using glosario?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims-tutorials#3]
See https://github.com/carpentries/glosario-r/. We have feedback that links to Wikipedia articles are distracting, but this might be more focused?

**Comment by petzi53** [comment]
Erroneously I linked to this issue when I mentioned `Tutorial no. 3` with a hash sign immediately before the number. 🤭  In the future, I will be more cautious with hash signs. 

But after saying this, it is also a good occasion to comment on your thoughts about a glossary:

Yes, I can understand that some students find Wikipedia links distracting. There is always too much (and irrelevant) text to read for the special problem at hand.

But generally, I think each textbook should have its own glossary. For me, this would be necessary for a self-contained product, even if you can find similar glossaries in many other places. Students should have the possibility to look up terms via a glossary index as an annex at the end of the book.

If the ims-book would have a glossary, then the online (HTML) version could also serve as an anchor where other material (such as the ims-tutorial) could link to it or (even better) where users could hover over the terms and get a short definition from the glossary as a tooltip. With a tooltip, you wouldn't be distracted so much as you remain on the same page/place and do not disrupt the reading flow as with footnotes or hyperlinks.

I still have to investigate the carpentries package you are referring to. At the moment, I always got the error message, "Some references are slugs that are not found".

**Comment by mine-cetinkaya-rundel** [comment]
Closing this issue since we didn't get much traction on it so far.
