### ISSUE TITLE
Move data files into openintro package

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroStat/ims-tutorials#4]
The following might not be an exhaustive list.

- Tutorial 2: cars04.csv
- Tutorial 2: life_exp.csv
- Tutorial 2: comics.csv
- Tutorial 4: nyc.csv on Zagat ratings, comes from https://gattonweb.uky.edu/sheather/book/docs/datasets/nyc.csv
- Tutorial 7: gss_wordsum_class.csv
- Tutorial 7: manhattan.csv
- Tutorial 6: iran.csv
- Tutorial 6: iowa.csv
- Tutorial 8: twins.csv (comes from Andrew, I have no idea where he got it: http://andrewpbray.github.io/data/twins.csv)
- Tutorial 8: LAhomes.csv (comes from Andrew, I think he might have scraped it?? http://andrewpbray.github.io/data/LA.csv)
- Tutorial 8: restNYC.csv almost positive this is the exact same data as nyc.csv from tutorial 4
- Tutorial 8: movies.tsv from http://www.rossmanchance.com/iscam2/data/movies03.txt

**Comment by mine-cetinkaya-rundel** [comment]
Also ucb_admit

**Comment by petzi53** [comment]
Also MedGPA from Stat2Data package in [tutorial 3, lesson 09](https://openintro.shinyapps.io/ims-03-model-09/#section-what-is-logistic-regression).

**Comment by mine-cetinkaya-rundel** [comment]
@npaterno - I wonder if this is something data hunters can help with?

**Comment by npaterno** [comment]
@mine-cetinkaya-rundel We can definitely do that! Do you have copies of the csv files that don't have links?

**Comment by mine-cetinkaya-rundel** [comment]
@npaterno They should all be in the respective data folders, let me know if you have difficulty locating them.

**Comment by npaterno** [comment]
@mine-cetinkaya-rundel Apologies for the delay. I should have this wrapped up and PR submitted to openintro by tomorrow afternoon.
