### ISSUE TITLE
Survey data without context in exercises

### ISSUE THREAD

**Issue by szimmer** [OpenIntroStat/ims-tutorials#61]
In the Statistical inference tutorials, the GSS data is used. A subsample of the data from NORC is used for exercises. It's not clear how that subsample is selected - not important for students. However, it is important to note that this data DOES come from a survey. 

Suggestions to improve this include:
- Ignore the multi year data, only introduce the 2016 data. The multi-year data is never used
- Tie it back to the **Sampling strategies and experimental design** and discuss stratification/clustering that is used in the 2016 GSS and/or include the 2016 GSS as an example in that section.
- Mention that this data comes from a complex survey design and appropriate inference would account for this design. The methods used in these tutorials are appropriate for simple random surveys or experimental data. SRS data is very rare in practice. More complex methods should be used for complex survey data. _Not in scope for this course but the `srvyr` package would provide the easiest way to transition students in a more advanced course to do this._

**Comment by mine-cetinkaya-rundel** [comment]
Thank you @szimmer, I've addressed this based on your suggestions!
